[[redirects]]
from = "/privacy-policy"
to = "https://bwhazel.uk/Privacy-Policy"
status = 200

[[redirects]]
from = "/sites"
to = "https://bwhazel.uk/Site-List"
status = 200

[[redirects]]
from = "/*"
to = "https://bwhazel.uk"
status = 200