site_name: BWHazel Info
copyright: Copyright &copy; Benedict W. Hazel, 2009-2021.  All views expressed are my own.  Site Version 1.0.1.
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs