site_name: BWHazel Info
copyright: Copyright &copy; Benedict W. Hazel, 2009-2025.  All views expressed are my own.  Site Version 1.2.3.
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
extra:
  metaThemeColour: "#3f51b5"